#This is the xp required to gain a level. It is the same for all classes, since
#different race/class combinations gain xp at different rates.
char_level_xp_req = {
    2:750,
    3:833,
    4:1055,
    5:1758,
    6:2930,
    7:4884,
    8:8140,
    9:13566,
    10:22610,
    11:37684,
    12:62806,
    13:104677,
    14:211693
}


char_race_traits = {
    "human":{"min_str":9,
             "max_str":19,
             "min_int":8,
             "max_int":18,
             "min_pie":8,
             "max_pie":18,
             "min_vit":9,
             "max_vit":19,
             "min_agi":8,
             "max_agi":18,
             "min_luk":8,
             "max_luk":18
            },
    "elf":{"min_str":7,
           "max_str":17,
           "min_int":10,
           "max_int":20,
           "min_pie":10,
           "max_pie":20,
           "min_vit":7,
           "max_vit":17,
           "min_agi":9,
           "max_agi":19,
           "min_luk":8,
           "max_luk":18
          }
}

char_race_xp_rate = {
    "human":{"fighter":4,
             "mage":5,
             "priest":5,
             "thief":7,
             "alchemist":11,
             "bishop":15,
             "bard":7,
             "ranger":4,
             "psionic":14,
             "valkyrie":10,
             "samurai":14,
             "lord":24,
             "monk":16,
             "ninja":28
            },
    "elf":{"fighter":6,
           "mage":3,
           "priest":3,
           "thief":6,
           "alchemist":9,
           "bishop":11,
           "bard":5,
           "ranger":8,
           "psionic":16,
           "valkyrie":11,
           "samurai":14,
           "lord":23,
           "monk":15,
           "ninja":27
          }
}

char_class_traits = {
    "fighter":{"preferred_stat":"strength",
               "hp_bonus":5,
               "min_str":12,
               "min_agi":0,
               "min_int":0,
               "min_vit":0,
               "min_pie":0,
               "min_luk":0,
               "AC":1,
               "THAC0mult":1
              },
    "mage":{"preferred_stat":"intelligence",
            "hp_bonus":1,
            "min_str":0,
            "min_agi":0,
            "min_int":12,
            "min_vit":0,
            "min_pie":0,
            "min_luk":0,
            "AC":1,
            "THAC0mult":0.5
           },
    "priest":{"preferred_stat":"piety",
              "hp_bonus":3,
              "min_str":0,
              "min_agi":0,
              "min_int":0,
              "min_vit":0,
              "min_pie":12,
              "min_luk":0,
              "AC":1,
              "THAC0mult":.75
             }
}
